### ISSUE TITLE
Using tasks loaded from File>Import... requires that the Activation be reset

### ISSUE THREAD

**Issue by cancub** [repeats/Repeat#13]
I was using 3.4.1 and decided to upgrade to 3.8.1. I exported "All Files" into the standard .zip, started up 3.8.1, imported the .zip and switched to this task group. When I try to use the activation for any of the tasks, it doesn't work. To get any of them to work I need to manually re-add the desired activation.

**Comment by hptruong93** [comment]
I'll take a look, but ideally you shouldn't be exporting and importing the tasks when switching version.

The new binary (.jar) should pick up the current configuration and convert it to the new version (if there is a new config version). Everything should stay the same. If you're paranoid that the new binary will screw up, you can always zip the current directory as backup.

**Comment by cancub** [comment]
Fair enough. It might be an issue if someone only has the .zip to work with rather than the original directory.

**Comment by hptruong93** [comment]
Fixed with 55448119f06df5849cf01613f79d3cae4aa51c73
Registering new tasks' activations after import. Ignore if there's already an existing activation.
