### ISSUE TITLE
Can't start Repeat_3_8_1.jar in Windows 7 after install jre-8u161-windows-x64.exe

### ISSUE THREAD

**Issue by vanloc0301** [repeats/Repeat#15]
Hi, I installed jre on Windows 7.

But I can't run Repeat. Did it require any additional application?

**Comment by vanloc0301** [comment]
I install JRE version 8u161. 
OS: Windows 7 x64.
Repeat: v3.8.1

I run Repeat like program in Windows. So, I install Java Runtime Environment to execute Repeat like .exe file.

It doesn't show any message or error.

I click on Repeat_3_8_1 and don't show anything.

You can see the icon of JRE:

![untitled](https://user-images.githubusercontent.com/4168981/36738945-51d9cf8e-1c11-11e8-8dc9-b6cf11fd4171.png)

Before, I installed both JDK and JRE on my Windows machine.
But it has the same error is: click to `.jar` file and doesn't show anything. I think the problem can because of my Windows. So, I install Windows. At the current time, my laptop runs in fresh Windows.

I run the problem, it shows a folder like resources. In this folder have folder python.

So, I install Python 3.6.4 with hopes it will run.

But it doesn't show anything when I tried to execute this .jar.

2 year ago, I see your repo is trending on Github, I was run your `jar` build and it works perfectly.
Today, I need using your build to optimize my work. I can't find any information about the error to report.

I was recorder my screen to describe my problem (about 1 minutes, hope you watch):
![gif](https://i.imgur.com/JTcx9RM.gif)

English is not my main language. You may have some confusion. So sorry about that.

**Comment by vanloc0301** [comment]
Hi @hptruong93 ,

I run successfully with the method:

Run cmd, type `java -jar Repeat_3_8_1.jar` and it works.

At next launch, I only double-click to `.jar` file and its working.

I don't know the problem at here. But it working perfectly. Thank you very much.

Your repo is awesome. :+1:

**Comment by hptruong93** [comment]
I'll update to include a log file at startup instead of having the output directed to stdout so that we can trace down problems like this.
