### ISSUE TITLE
Allow user to configure port number

### ISSUE THREAD

**Issue by cancub** [repeats/Repeat#19]
There's a server process that I need to run on my machine and the clients with which it communicates are expecting to contact port 9999 -- the port that Repeat uses. I can't change the port being sought by the clients, so it would be nice to have the option of changing Repeat's port via the UI.

**Comment by hptruong93** [comment]
Should be fixed with bc15ea7716f2cc3142075835eba637eea10f10dc

**Comment by cancub** [comment]
Thanks, HP. You da best
