### ISSUE TITLE
Make Repeat window text and buttons scale with desktop resolution

### ISSUE THREAD

**Issue by cancub** [repeats/Repeat#20]
It's a tad difficult to read what's going on sometimes.

![selection_001](https://user-images.githubusercontent.com/8180852/41975735-8f3a328e-79e9-11e8-9276-13aaf254c3fc.png)

**Comment by hptruong93** [comment]
Did you just get a 4K monitor? :)
For automated scaling to work, I'll need to port the GUI to JavaFX which is non trivial work. So this might take a while.
Meanwhile you can still edit code using your editor by clicking the third button on the left just above the code section.

**Comment by cancub** [comment]
Understood. No 4K for me, I try to stay one behind the current standard in order to save money ;)

**Comment by hptruong93** [comment]
Latest release with web UI should solve this problem.
https://github.com/repeats/Repeat/releases/tag/v5.0
