### ISSUE TITLE
Standalone Nativehook project

### ISSUE THREAD

**Issue by macdevign** [repeats/Repeat#21]
"Replaced JNativeHook with new NativeHook included in the binary. JNativeHook dependency will be completely remove in the next few releases"

Assuming that NativeHook is direct replacement for JNativeHook, is it possible you make it as standalone library much like JNativeHook ? I can't help thinking that JNativeHook development has stagnant and it has some hang issue after some time running on Mac Mojave. Probably your library is much stable and reliable.

thank

**Comment by hptruong93** [comment]
This is possible. However, there are two things to keep in mind:
1) I'll still need to figure out how to use X11 for hook (current linux hook listens directly  to low level device files which require root access). This is Linux only so OSX shouldn't be affected.
2) I will not support keyboards for languages other than English (e.g. French, Arabic, Russian, ...). I simply don't have the resources to develop with these keyboards, and it is not the main goal of Repeat.

It will probably take a few weeks to refactor the code out and extract it as a standalone library.

**Comment by macdevign** [comment]
That's great :}
For #2, it is fine going by 80:20 rule.

**Comment by hptruong93** [comment]
This is now available under https://github.com/repeats/SimpleNativeHooks/releases
