### ISSUE TITLE
Unable to find documentation or any examples

### ISSUE THREAD

**Issue by NGenetzky** [repeats/Repeat#22]
This project looks very interesting, but it's very hard to find documentation or examples. If these things exist could you add a link in the project's README or comment back on this issue?

**Comment by hptruong93** [comment]
Hi,

I've added the wiki section (and reference it in README).
https://github.com/repeats/Repeat/wiki

Let me know if you have any other question on usage.

**Comment by NGenetzky** [comment]
Looks good, thank you.
