### ISSUE TITLE
I just want to record and create it as a task. How do I do that?

### ISSUE THREAD

**Issue by marnel-estrada** [repeats/Repeat#26]
I tried recording some mouse movements, compiled then add as a task. Nothing is happening when I play the task.

**Comment by hptruong93** [comment]
Plain record and replay example can be found here
https://github.com/repeats/Repeat/wiki/Getting-started#record--replay

If you want to save the recording as task, you'll need to generate the code first. To do that, finish your recording, then choose Tools --> Generate Source (top right menu), then compile and add the new task.

**Comment by marnel-estrada** [comment]
Thank you! This is really helpful.

**Comment by hptruong93** [comment]
I added this instruction to the wiki page.
