### ISSUE TITLE
How can I run a script from my command prompt?

### ISSUE THREAD

**Issue by ahmedmohiduet** [repeats/Repeat#31]
I can record my mouse keyboard actions and clicking on 'Tools/Generate Sources' creating script for my actions. So, how can I execute a Repeat script from my command prompt? It appears the documentation lacking information regarding this.

**Comment by hptruong93** [comment]
Could you elaborate more on why you want to trigger the task from command prompt?

The way to do this is to assign a shared variable https://github.com/repeats/Repeat/wiki/Getting-started#shared-variable as a task activation, then use the CLI (https://github.com/repeats/Repeat/wiki/Command-Line-Interface-(CLI)) to set the variable. For example

java -jar Repeat.jar  cli variable -a get -s global -n variable_name -v someval

**Comment by ahmedmohiduet** [comment]
@hptruong93 : Thank you for prompt response. It had'nt occurred to me there can be different ways a script can be run. I'm still going through documentation and kind off unsure about its overall workflow. (y)
