### ISSUE TITLE
cannot understand the 'getting started' instructions

### ISSUE THREAD

**Issue by ven-u** [repeats/Repeat#32]
The instructions read:
Just download the latest version, put the jar in a separate directory, and run it with java. 

    Which jar file?  There is none in the root directory of the downloaded zip file.  Other documentation says "repeat.jar" but I can't find it anywhere....

Note that since Java 9, the jar file must be launched from a JDK (as opposed to a JRE) to be able to compile file. The workaround used in Java 8 and before to set Java home no longer works.

I'm running linuxmint 20.1.  My java: 

    $ java --version \ openjdk 11.0.10 2021-01-19 \ OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04) \ OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

Would appreciate some help with this. Repeat.jar may be easier for me than autokey.

Thanks

**Comment by hptruong93** [comment]
The jar file can be downloaded from https://github.com/repeats/Repeat/releases/latest.
For example
![image](https://user-images.githubusercontent.com/3408713/113588766-904b0700-95fe-11eb-9046-4cc42dc30823.png)

You can also download it from Sourceforge: https://sourceforge.net/projects/repeat1/
