### ISSUE TITLE
unable to switch compile language

### ISSUE THREAD

**Issue by rwebber** [repeats/Repeat#33]
The UI does allow me to change either the compiler path or configure compiler.

**errors reported:**
Apr 12, 2021 6:11:50 PM core.webui.server.handlers.internals.menu.MenuGetCompilerPathActionHandler handleAllowedRequestWithBackend
INFO: Current compiler does not support getting/setting path.
Apr 12, 2021 6:11:50 PM core.webui.webcommon.HttpServerUtilities prepareStringResponse
WARNING: HTTP response with code 400: Current compiler does not support getting/setting path.
Apr 12, 2021 6:11:54 PM core.webui.webcommon.HttpServerUtilities prepareStringResponse
WARNING: HTTP response with code 400: Current language MANUAL_BUILD does not support changing configuration.

I have edited the config.json file to include my Python path in the "local_compilers" section, and I can see on startup of Repeat that python is found.

**log:**
INFO: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Initialization finished. UI server is at http://localhost:65401
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Apr 12, 2021 6:14:01 PM core.ipc.repeatServer.ControllerServer$1 run
INFO: New client accepted: 127.0.0.1:52009
Apr 12, 2021 6:14:01 PM core.ipc.repeatClient.IPCClientService$1 run
INFO: [Thread-9] - [PYTHON][INFO][repeat_lib.py][79] - Successfully started python client
Apr 12, 2021 6:14:01 PM core.ipc.repeatServer.processors.TaskProcessorManager identifyProcessor
INFO: Identified remote compiler python

How can I switch to using python? I need to integrate Repeat with PyTest among other modules.
Thanks

**Comment by hptruong93** [comment]
Did the instruction in https://github.com/repeats/Repeat/wiki/Coding-languages#python not work?

I think you accidentally switched back to the MANUAL_BUILD language when refreshing the page. The UI automatically switches to the language of the currently selected task on page load, so you may need to switch it manually back to Python.

**Comment by rwebber** [comment]
Step 1 in the instructions says 'Switch compiling language to Python', I don't see this option previously. 
I didn't expect it to be in Tools. I got caught up on the warnings I got from the other options.

It is working as expected for me know. thanks

Is there any delimiter that I can use to add more Python to the end of a recorded sequence?
I would like to add some python to run after the mouse sequence is finished, and I would like to be able to re-record the sequence if needed without losing my Python code.. is that possible?

**Comment by hptruong93** [comment]
Have you tried out the code generation feature?
Instruction at the end of https://github.com/repeats/Repeat/wiki/Getting-started#record--replay

Basically make sure the language is Python, then record an action and then choose Tools --> Generate source on the top right drop down menu. Once the source code has been generated you can add whatever you want at the end.

**Comment by hptruong93** [comment]
I'll close this due to inactivity.
