### ISSUE TITLE
Dạ lỗi lúc repeat bị lặp ký tự

### ISSUE THREAD

**Issue by nhanhthat** [repeats/Repeat#34]
Lúc record em type "abc" xong repeat nó sẽ type "aabbcc". Em đang xài mac m1, và đã thử nhiều Repeat version cũ hay mới đều bị lỗi này ạ.

**Comment by hptruong93** [comment]
Em mới thử lại sáng nay trên Mac OS 11.3.1 bản Repeat 5.6 vẫn chạy Record Replay bình thường.
Bác thử lại xem có bật gõ tiếng Việt hay không? Java đang chạy là bản mấy?

**Comment by nhanhthat** [comment]
Dạ em tắt gõ tiếng Việt thì thấy oke rồi ạ, em cám ơn bác ạ.
