### ISSUE TITLE
show ui not working

### ISSUE THREAD

**Issue by UDG-yt** [repeats/Repeat#35]
when I click show UI it opens the web page but I can't connect to it for some reason?
I just want to play fireboy and water girl but my up arrow is broken :(
<img width="1440" alt="Screen Shot 2022-01-11 at 10 41 09 PM" src="https://user-images.githubusercontent.com/74624966/149065217-47699732-0dcc-45ef-8bcd-b2d751d9c6fc.png">

**Comment by UDG-yt** [comment]
> when I click show UI it opens the web page but I can't connect to it for some reason <img alt="Screen Shot 2022-01-11 at 10 41 09 PM" width="1440" src="https://user-images.githubusercontent.com/74624966/149065217-47699732-0dcc-45ef-8bcd-b2d751d9c6fc.png"> ?

**Comment by hptruong93** [comment]
Is there any log? Can you try opening this in a terminal (not double clicking) to see the log?

**Comment by hptruong93** [comment]
To clarify, I mean try opening Repeat in a terminal
`java -jar Repeat.jar`

so that we can see the log

**Comment by hptruong93** [comment]
Close due to inactivity.
