### ISSUE TITLE
New function

### ISSUE THREAD

**Issue by wholespace** [repeats/Repeat#37]
Hello,
Thank you so much for allowing me to use this program.
It seems that the record for the mouse scroll event is not progressing.
Could you please attach this function?

Thank you.

**Comment by hptruong93** [comment]
This has been asked before here https://github.com/repeats/Repeat/issues/4

You can certainly emulate mouse scrolling and insert that into your code later on.

The summary of the previous issue is that Java scrolling API is different from the native event. The Java scrolling API uses the mouse "notch" while the native event reports scrolling distance, which doesn't translate very well.
