### ISSUE TITLE
Doesn't boot

### ISSUE THREAD

**Issue by 32bitx64bit** [repeats/Repeat#40]
Feb 02, 2023 6:18:39 PM frontEnd.MainBackEndHolder <init>
WARNING: System tray is not supported!
Feb 02, 2023 6:18:39 PM core.controller.Core local
SEVERE: Exception constructing controller
java.awt.AWTException: headless environment
	at java.desktop/java.awt.Robot.checkHeadless(Robot.java:179)
	at java.desktop/java.awt.Robot.<init>(Robot.java:96)
	at core.controller.Core.local(Core.java:27)
	at core.controller.CoreProvider.getLocal(CoreProvider.java:30)
	at core.recorder.Recorder.<init>(Recorder.java:43)
	at frontEnd.MainBackEndHolder.<init>(MainBackEndHolder.java:122)
	at frontEnd.MainFrontEnd.run(MainFrontEnd.java:32)
	at main.Main.main(Main.java:11)

**Comment by 32bitx64bit** [comment]
To clarify im on Ubuntu budgie 22.04.1 64bit on X11

**Comment by hptruong93** [comment]
java.awt.AWTException: headless environment

Could you provide more details on the setup? Are you trying to launch this from a different machine connected to the Ubuntu machine?
In general, you can't run this via headless environment. X11/ssh doesn't provide access to the remote machine's mouse/keyboard.
There's a specific section in FAQ about headless
https://github.com/repeats/Repeat#why-is-this-only-available-in-non-headless-system

**Comment by 32bitx64bit** [comment]
Im not using SSH to run, im on native hardware

**Comment by hptruong93** [comment]
Let me download a fresh Ubuntu Budgie and try.

Meanwhile, if possible, can you try compiling and running the following simple Java program?

```
import java.awt.AWTException;
import java.awt.Robot;

public class Test {
  
    public static void main(String[] args) throws AWTException  {
        Robot robot = new Robot();
        robot.delay(1000);
        System.out.println("test");
      
        }
    }
}
```

Basically write the content into Test.java, then run
$javac Test.java
(you may need to set the classpath after compilation to point to add the current directory)
$java Test

Testing in an IDE is also fine. I just want to see whether java.awt.Robot can be created.

**Comment by hptruong93** [comment]
My internet was slow so I couldn't test for the past few days.

I just downloaded an tried running on a fresh installation of Ubuntu Budgie with "default-jdk" (sudo apt install default-jdk) and it works fine.

How did you boot the JAR file? Did you use `java -jar Repeat.jar`?
Can you share the output of `java -version` too?

**Comment by 32bitx64bit** [comment]
I launched via the instructions. I'll try giving defualt jdk a try.

**Comment by 32bitx64bit** [comment]
Been busy but using default JDK worked
