### ISSUE TITLE
Posibility to save mouse & keyboard records

### ISSUE THREAD

**Issue by pro100kryto** [repeats/Repeat#42]
The mouse and keyboard recorder is working very nice, but there is no way to save it as new task or to compile. I think every new recording should be converted to a sequence of actions or to a compiled task directly. That important functionality is missing.

**Comment by hptruong93** [comment]
Have you tried following this?

From https://github.com/repeats/Repeat/wiki/Getting-started#record--replay
To generate source code out of a recorded action, choose Tools --> Generate source on the top right drop down menu. Once the source code has been generated, you can use the [Creating and managing tasks](https://github.com/repeats/Repeat/wiki/Getting-started#task_creation) section below to save the task.

**Comment by pro100kryto** [comment]
Ohh, thank you. I just nad to press the "Generate source" option to have it.
It is not obvious. Why to not generate source just after recording automatically?

**Comment by hptruong93** [comment]
> Why to not generate source just after recording automatically?
Because the UI is a webpage. When you open 2 tabs (both going to the http://localhost:65401 page), start recording on one tab, and stop recording on the other, things start getting messy and quite hard to implement from a technical perspective.
