### ISSUE TITLE
Add support for multiple screens

### ISSUE THREAD

**Issue by cancub** [repeats/Repeat#7]
It would appear that the mouse actions are replayed only on the primary display in Ubuntu 16.04, regardless of where the recording took place or on which display the cursor currently exists.

**Comment by hptruong93** [comment]
From my experience, recording and replay work fine on multiple displays on Windows. I'll check on Ubuntu as soon as I have access to multiple displays on this OS.

**Comment by hptruong93** [comment]
Problem not reproducible on Ubuntu 16.04
